name: AnÃ¡lise de CÃ³digo

on: push

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    environment: actions

    steps:
      - name: Checkout âœ…
        uses: actions/checkout@v3

      - name: Setup ðŸ—
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install âš™ï¸
        run: npm install

      - name: Install Junit
        run: npm install --save-dev karma-junit-reporter

      - name: Build ðŸ› 
        run: npm run build

      - name: Test ðŸ“‹
        run: npm run test:prod

      - name: Test Printing Test Report
        run: cat test-reports/TESTS.xml

      - name: Remove src/app/app.constant.ts from lcov.info
        run: |
          grep -v "SF:src/app/app.constant.ts" coverage/unb-tv-frontend/lcov.info > coverage/unb-tv-frontend/lcov_temp.info
          mv coverage/unb-tv-frontend/lcov_temp.info coverage/unb-tv-frontend/lcov.info
          
      - name: Executa SonarCloud Scan
        if: ${{ always() }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.API_TOKEN_GITHUB}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
